const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAIL: 'IMAGES_LOAD_FAIL',
    TOGGLE_FAVORITE: 'IMAGES_TOGGLE_FAVORITE',
    TOGGLE_FAVORITES_TAB: 'IMAGES_TOGGLE_FAVORITES_TAB',
    DELETE_IMAGE: 'IMAGES_DELETE',
};

const STATS = {
    LOAD: 'STATS_LOAD',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_FAIL: 'STATS_LOAD_FAIL',
};

export { IMAGES, STATS };
